image:
  repository: ghcr.io/piscoaq/api-for-game
  tag: main
  pullPolicy: Always

httpRoute:
  enabled: false

env:
  - name: MONGO_URI
    valueFrom:
      secretKeyRef:
        name: mongodb-gameapi-credentials
        key: connectionString

service:
  port: 3000

livenessProbe:
  httpGet:
    path: /api/health
    port: http
readinessProbe:
  httpGet:
    path: /api/health
    port: http
